import React from 'react';
import { useAuth } from '../hooks/useAuth';
import { useWorkOrders } from '../hooks/useWorkOrders';
import { Card } from '../components/ui/Card';
import { Mail, Briefcase, Building, Wallet, Wrench, CheckCircle2 } from 'lucide-react';

export const Profile: React.FC = () => {
    const { perfil } = useAuth();
    const { orders } = useWorkOrders();

    // Calculate personal stats
    const myOrders = orders.filter(o => o.mecanico_id === perfil?.id);
    const completedOrders = myOrders.filter(o => o.estado_proceso === 'lista' || o.estado_proceso === 'entregada' || o.estado_proceso === 'pagada').length;

    // Calculate total generated by this mechanic (sum of totals of orders assigned to them)
    // Note: This is a rough estimation. In a real scenario, we might want to sum only the labor or specific commissions.
    // For now, seeing the total volume handled by the mechanic is a good metric.
    const totalHandled = myOrders.reduce((acc, o) => acc + (o.total || 0), 0);

    return (
        <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in duration-500">
            <div>
                <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Mi Perfil</h1>
                <p className="text-slate-500 font-medium">Información personal y estadísticas de desempeño</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {/* Identity Card */}
                <div className="md:col-span-1 space-y-6">
                    <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm text-center relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-full h-24 bg-gradient-to-br from-blue-600 to-indigo-700"></div>
                        <div className="relative mt-12 mb-4">
                            <div className="w-24 h-24 mx-auto bg-white rounded-full p-1 shadow-xl">
                                <div className="w-full h-full rounded-full bg-slate-100 flex items-center justify-center text-3xl font-black text-blue-600 uppercase">
                                    {perfil?.nombre?.substring(0, 2) || '??'}
                                </div>
                            </div>
                        </div>
                        <h2 className="text-xl font-bold text-slate-900">{perfil?.nombre}</h2>
                        <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-blue-50 text-blue-700 rounded-full text-xs font-bold uppercase tracking-wider mt-2">
                            <Briefcase size={12} /> {perfil?.rol}
                        </div>

                        <div className="mt-6 space-y-3 text-left">
                            <div className="flex items-center gap-3 text-slate-600 text-sm p-3 bg-slate-50 rounded-xl">
                                <Mail size={16} className="text-slate-400" />
                                <span className="truncate">{perfil?.email}</span>
                            </div>
                            <div className="flex items-center gap-3 text-slate-600 text-sm p-3 bg-slate-50 rounded-xl">
                                <Building size={16} className="text-slate-400" />
                                <span className="truncate">ID Taller: {perfil?.negocio_id?.slice(0, 8)}...</span>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Stats & Activity */}
                <div className="md:col-span-2 space-y-6">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <div className="bg-white p-5 rounded-3xl border border-slate-100 shadow-sm flex items-center gap-4">
                            <div className="p-3 bg-blue-50 text-blue-600 rounded-2xl">
                                <Wrench size={24} />
                            </div>
                            <div>
                                <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Órdenes Asignadas</p>
                                <p className="text-2xl font-black text-slate-900">{myOrders.length}</p>
                            </div>
                        </div>
                        <div className="bg-white p-5 rounded-3xl border border-slate-100 shadow-sm flex items-center gap-4">
                            <div className="p-3 bg-green-50 text-green-600 rounded-2xl">
                                <CheckCircle2 size={24} />
                            </div>
                            <div>
                                <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Completadas</p>
                                <p className="text-2xl font-black text-slate-900">{completedOrders}</p>
                            </div>
                        </div>
                        <div className="bg-white p-5 rounded-3xl border border-slate-100 shadow-sm flex items-center gap-4 sm:col-span-2">
                            <div className="p-3 bg-indigo-50 text-indigo-600 rounded-2xl">
                                <Wallet size={24} />
                            </div>
                            <div>
                                <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Volumen Gestionado (Total Ventas)</p>
                                <p className="text-2xl font-black text-slate-900">${totalHandled.toLocaleString('es-CL')}</p>
                            </div>
                        </div>
                    </div>

                    <Card title="Últimas Órdenes Asignadas">
                        {myOrders.length === 0 ? (
                            <div className="text-center py-8 text-slate-500">
                                No tienes órdenes asignadas recientemente.
                            </div>
                        ) : (
                            <div className="space-y-3">
                                {myOrders.slice(0, 5).map(order => (
                                    <div key={order.id} className="flex items-center justify-between p-3 hover:bg-slate-50 rounded-xl transition-colors border border-transparent hover:border-slate-100">
                                        <div className="flex items-center gap-3">
                                            <div className="w-10 h-10 rounded-lg bg-slate-100 flex items-center justify-center text-slate-500 font-bold">
                                                {order.id.slice(0, 2)}
                                            </div>
                                            <div>
                                                <p className="font-bold text-slate-900 text-sm">{order.bici_modelo}</p>
                                                <p className="text-xs text-slate-500">{order.cliente_nombre}</p>
                                            </div>
                                        </div>
                                        <div className="text-right">
                                            <span className={`inline-flex px-2 py-1 rounded-full text-[10px] font-bold uppercase ${order.estado_proceso === 'lista' ? 'bg-green-100 text-green-700' :
                                                order.estado_proceso === 'en_proceso' ? 'bg-blue-100 text-blue-700' : 'bg-slate-100 text-slate-600'
                                                }`}>
                                                {order.estado_proceso || 'Pendiente'}
                                            </span>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </Card>
                </div>
            </div>
        </div>
    );
};
